name: React Native CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint
      run: npm run lint || echo "No linting configured"
    
    - name: Create Firebase config stub
      run: |
        echo "export default {
          apiKey: 'dummy-key',
          authDomain: 'dummy-domain',
          projectId: 'dummy-project',
          storageBucket: 'dummy-bucket',
          messagingSenderId: 'dummy-sender',
          appId: 'dummy-app-id'
        };" > src/firebase/firebase-config-local.js
    
    - name: Build
      run: npm run build || echo "No build script configured"
    
    - name: Test
      run: npm test || echo "No tests configured"
